@Restaurants.API_HostAddress = https://localhost:7082
@token = CfDJ8KSgmYBPs4FLiJKae1GuqBg7Un2CGZo9ofY7kPmj0izWpMIxs3yzCcVH8R5YZqubjuqkmEmLJ4-PilHTMOdZ-_z4JU-i1JY07ThialMtI4kAhCtgAXFZxMgdEyqg4gAq35IlmX4L1bkhwOj2whwcmRd0VpwhXG475SjyxbD9tEHgtizTI5fx4x2ZOgbyUjZp8AR74wWfbyY7OfarInvrevhw64aWmE9NnEoCuyBSGgee3EfBBqab6_s9JHIiCJjSwFwYMVF_D2ngLd6Jlyr7UNSdzTCK4bAoPliNUpj860iZ9ZGek5AnSEoZMUFBjE775EB6uabuprmLYvEtN9omAn1L6A9O3z-2jaPeAdcx-jnzPXNnlCW4VYQnvyjKklbSZQBDtsv4_KYd_pjyxbrT8vbvsq0oVuALzvuzhqkmysuUHXBsPaYx8E7AJXSh8aC8v167vrLNR4CQPce3V_0JA64TNoH7ZqYWaSy_1twlBeORo09dEEaFQPwrNnPxVZhN9XoE8iPwYo_kLLCKGbiZxBvLqxJJbYy4-ok2W7obJIpKvXQu8kt7m3ji6v3pJ1WLureX6An95Pn3E38sCBSxJtBMdeNeYytyXwge1TfadfUuOoQykxUZYONGL_b4st43WywwRbb71HkJIzPsexH-s-crN13_qssaBpnAFHwEoU3zIMpG_IPn217rsCk-3idzSA



GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer{{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/5519ae79-f0b9-4db0-3d92-08dde63eedd4

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants


###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "restaurantName": "The Spice House",
  "description": "Authentic Indian cuisine with a modern twist.",
  "category": "Indian",
  "hasDelivery": true,
  "contactNumber": "+1-555-987-6543",
  "contactEmail": "info@spicehouse.com",
  "city": "San Francisco",
  "street": "123 Curry Lane",
  "postalCode": "94-107"
}

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{289a763b-2196-4440-b503-08dde1902add}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
    "id": "5519ae79-f0b9-4db0-3d92-08dde63eedd4",
    "restaurantName": "The Indian Spice",
    "description": "Authentic Indian cuisine with a Spicy twist.",
    "hasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "testuser@test.com",
  "password":"Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "testuser@test.com",
  "password":"Password1!"
}

